### ISSUE TITLE
Mac not running

### ISSUE THREAD

**Issue by wizerdo** [CmdrDats/igoki#105]
Using the latest MacOS version i get this:

Exception in thread "main" java.lang.NoClassDefFoundError: java/awt/event/FocusEvent$Cause
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6224)
	at java.awt.Component.access$500(Component.java:186)
	at java.awt.Component$3.run(Component.java:6178)
	at java.awt.Component$3.run(Component.java:6176)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Component.checkCoalescing(Component.java:6175)
	at java.awt.Component.<init>(Component.java:6144)
	at java.awt.Container.<init>(Container.java:285)
	at javax.swing.JComponent.<init>(JComponent.java:588)
	at javax.swing.JLabel.<init>(JLabel.java:160)
	at javax.swing.JLabel.<init>(JLabel.java:235)
	at seesaw.core.proxy$javax.swing.JLabel$Tag$fd407141.<init>(Unknown Source)
	at seesaw.core$label.invokeStatic(core.clj:1185)
	at seesaw.core$label.doInvoke(core.clj:1157)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at igoki.core$splash_BANG_.invokeStatic(core.clj:49)
	at igoki.core$splash_BANG_.doInvoke(core.clj:33)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at igoki.core$_main.invokeStatic(core.clj:81)
	at igoki.core$_main.doInvoke(core.clj:80)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at igoki.core.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: java.awt.event.FocusEvent$Cause
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 27 more

Do you have an idea what's going wrong?

**Comment by CmdrDats** [comment]
Hi, I remember seeing this - I suspect it's to do with an older version of java installed - if you open terminal and type `java -version` it should confirm it. This class was introduced in java 9.

Curious though - I have tested this with java 8 - I wonder if it's something specifically in the splash screen code.. I'll have a look.

**Comment by CmdrDats** [comment]
actually - I think I do understand the reason for this - if you're running java 8, and I compiled the jar with latest java 16 or 17, then main namespace would have done an ahead-of-time compile, probably binding to the availability of this class.

So. I'll just remove the splash screen and trim the core mainspace down and cut a new release tonight. Will comment on here as soon as I've done so.

**Comment by wizerdo** [comment]
Yes I downloaded JDK 17 which ran it successfully. although now I have another problem (see the new issue) ;)

**Comment by CmdrDats** [comment]
haha, ok - I've pushed this release: https://github.com/CmdrDats/igoki/releases/tag/0.7.1 for this issue xD

**Comment by CmdrDats** [comment]
hmm, i haven't seen a new issue now - still making it?

**Comment by wizerdo** [comment]
haha yeah, its actually an old issue as it turnes out. I can't grant permission with macOS Monterey to access the camera

**Comment by wizerdo** [comment]
so that is problem #64

**Comment by CmdrDats** [comment]
cool, i'll optimistically close this issue then :)
