### ISSUE TITLE
Igoki not working on Mac OS Sierra

### ISSUE THREAD

**Issue by MadDaimond** [CmdrDats/igoki#108]
The igoki not working on Macbook a1342, Mac OS X Sierra, java version "18" 2022-03-22.When I launch it the java icon appears for some seconds ant the suddenly quits. The log file is here:

`MacBook-Sergei:~ sergio$ cd /Users/sergio/Downloads 
MacBook-Sergei:Downloads sergio$ java -jar igoki.jar
апр. 10, 2022 11:17:31 AM nu.pattern.OpenCV$SharedLoader <init>
SEVERE: OpenCV.loadShared() is not supported in Java >= 12. Falling back to OpenCV.loadLocally().
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/sh/f02f7xc55h332yxy09bhhptm0000gp/T/opencv_openpnp14948910738569780376/nu/pattern/opencv/osx/x86_64/libopencv_java451.dylib: dlopen(/private/var/folders/sh/f02f7xc55h332yxy09bhhptm0000gp/T/opencv_openpnp14948910738569780376/nu/pattern/opencv/osx/x86_64/libopencv_java451.dylib, 1): Symbol not found: _AVVideoCodecTypeHEVC
  Referenced from: /private/var/folders/sh/f02f7xc55h332yxy09bhhptm0000gp/T/opencv_openpnp14948910738569780376/nu/pattern/opencv/osx/x86_64/libopencv_java451.dylib
  Expected in: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 in /private/var/folders/sh/f02f7xc55h332yxy09bhhptm0000gp/T/opencv_openpnp14948910738569780376/nu/pattern/opencv/osx/x86_64/libopencv_java451.dylib
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:330)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:326)
	at nu.pattern.OpenCV$LocalLoader$Holder.<clinit>(OpenCV.java:336)
	at nu.pattern.OpenCV$LocalLoader.getInstance(OpenCV.java:340)
	at nu.pattern.OpenCV.loadLocally(OpenCV.java:323)
	at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:217)
	at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:189)
	at nu.pattern.OpenCV$SharedLoader$Holder.<clinit>(OpenCV.java:261)
	at nu.pattern.OpenCV$SharedLoader.getInstance(OpenCV.java:265)
	at nu.pattern.OpenCV.loadShared(OpenCV.java:183)
	at igoki.core__init.load(Unknown Source)
	at igoki.core__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:488)
	at java.base/java.lang.Class.forName(Class.java:467)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at clojure.lang.RT.loadClassForName(RT.java:2240)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.lang.Util.loadWithClass(Util.java:251)
	at igoki.core.<clinit>(Unknown Source)`

**Comment by CmdrDats** [comment]
Curious, looks like an opencv native library issue - i wonder if Sierra is supported by it - I’ll look into upgrading to latest opencv library
